from enum import StrEnum


class EncounterClass(StrEnum):
    EMER = "EMER"
    IMP = "IMP"
    AMB = "AMB"
    VR = "VR"
    HH = "HH"


class EncounterStatus(StrEnum):
    PLANNED = "PLANNED"
    IN_PROGRESS = "IN_PROGRESS"
    FINISHED = "FINISHED"
    CANCELLED = "CANCELLED"
    ENTERED_IN_ERROR = "ENTERED_IN_ERROR"


class ClinicalRecordStatus(StrEnum):
    DRAFT = "DRAFT"
    FINAL = "FINAL"
    ENTERED_IN_ERROR = "ENTERED_IN_ERROR"


class ClinicalNoteType(StrEnum):
    PROGRESS = "PROGRESS"
    ADMISSION = "ADMISSION"
    ED = "ED"
    DISCHARGE = "DISCHARGE"
    OTHER = "OTHER"


class ParticipationType(StrEnum):
    ATTENDING = "ATTENDING"
    ADMITTING = "ADMITTING"
    CONSULTANT = "CONSULTANT"
    OTHER = "OTHER"


class ConditionCategory(StrEnum):
    PROBLEM_LIST_ITEM = "PROBLEM_LIST_ITEM"
    ENCOUNTER_DIAGNOSIS = "ENCOUNTER_DIAGNOSIS"


class ConditionClinicalStatus(StrEnum):
    ACTIVE = "ACTIVE"
    RECURRENCE = "RECURRENCE"
    RELAPSE = "RELAPSE"
    INACTIVE = "INACTIVE"
    REMISSION = "REMISSION"
    RESOLVED = "RESOLVED"


class ConditionVerificationStatus(StrEnum):
    UNCONFIRMED = "UNCONFIRMED"
    PROVISIONAL = "PROVISIONAL"
    DIFFERENTIAL = "DIFFERENTIAL"
    CONFIRMED = "CONFIRMED"
    REFUTED = "REFUTED"
    ENTERED_IN_ERROR = "ENTERED_IN_ERROR"


class ObservationCategory(StrEnum):
    VITAL_SIGNS = "VITAL_SIGNS"
    EXAM = "EXAM"
    OTHER = "OTHER"


class ObservationValueType(StrEnum):
    NUMERIC = "NUMERIC"
    TEXT = "TEXT"
    BOOLEAN = "BOOLEAN"
    CODED = "CODED"


class ObservationStatus(StrEnum):
    FINAL = "FINAL"
    AMENDED = "AMENDED"
    ENTERED_IN_ERROR = "ENTERED_IN_ERROR"


class ClinicalProvenanceSubjectType(StrEnum):
    ENCOUNTER = "ENCOUNTER"
    CLINICAL_NOTE = "CLINICAL_NOTE"
    CONDITION = "CONDITION"
    OBSERVATION = "OBSERVATION"


class ClinicalAuditAction(StrEnum):
    ENCOUNTER_CREATED = "ENCOUNTER_CREATED"
    ENCOUNTER_STATUS_CHANGED = "ENCOUNTER_STATUS_CHANGED"
    CLINICAL_NOTE_CREATED = "CLINICAL_NOTE_CREATED"
    CLINICAL_NOTE_UPDATED = "CLINICAL_NOTE_UPDATED"
    CLINICAL_NOTE_FINALIZED = "CLINICAL_NOTE_FINALIZED"
    CLINICAL_NOTE_ENTERED_IN_ERROR = "CLINICAL_NOTE_ENTERED_IN_ERROR"
    CONDITION_CREATED = "CONDITION_CREATED"
    CONDITION_STATUS_CHANGED = "CONDITION_STATUS_CHANGED"
    CONDITION_ENTERED_IN_ERROR = "CONDITION_ENTERED_IN_ERROR"
    OBSERVATION_CREATED = "OBSERVATION_CREATED"
    OBSERVATION_AMENDED = "OBSERVATION_AMENDED"
    OBSERVATION_ENTERED_IN_ERROR = "OBSERVATION_ENTERED_IN_ERROR"
