from enum import StrEnum


class EncounterClass(StrEnum):
    EMER = "EMER"
    IMP = "IMP"
    AMB = "AMB"
    VR = "VR"
    HH = "HH"


class EncounterStatus(StrEnum):
    PLANNED = "PLANNED"
    IN_PROGRESS = "IN_PROGRESS"
    FINISHED = "FINISHED"
    CANCELLED = "CANCELLED"
    ENTERED_IN_ERROR = "ENTERED_IN_ERROR"


class ClinicalRecordStatus(StrEnum):
    DRAFT = "DRAFT"
    FINAL = "FINAL"
    ENTERED_IN_ERROR = "ENTERED_IN_ERROR"


class ClinicalNoteType(StrEnum):
    PROGRESS = "PROGRESS"
    ADMISSION = "ADMISSION"
    ED = "ED"
    DISCHARGE = "DISCHARGE"
    OTHER = "OTHER"


class ParticipationType(StrEnum):
    ATTENDING = "ATTENDING"
    ADMITTING = "ADMITTING"
    CONSULTANT = "CONSULTANT"
    OTHER = "OTHER"


class ConditionCategory(StrEnum):
    PROBLEM_LIST_ITEM = "PROBLEM_LIST_ITEM"
    ENCOUNTER_DIAGNOSIS = "ENCOUNTER_DIAGNOSIS"


class ConditionClinicalStatus(StrEnum):
    ACTIVE = "ACTIVE"
    RECURRENCE = "RECURRENCE"
    RELAPSE = "RELAPSE"
    INACTIVE = "INACTIVE"
    REMISSION = "REMISSION"
    RESOLVED = "RESOLVED"


class ConditionVerificationStatus(StrEnum):
    UNCONFIRMED = "UNCONFIRMED"
    PROVISIONAL = "PROVISIONAL"
    DIFFERENTIAL = "DIFFERENTIAL"
    CONFIRMED = "CONFIRMED"
    REFUTED = "REFUTED"
    ENTERED_IN_ERROR = "ENTERED_IN_ERROR"


class ObservationCategory(StrEnum):
    VITAL_SIGNS = "VITAL_SIGNS"
    EXAM = "EXAM"
    OTHER = "OTHER"


class ObservationValueType(StrEnum):
    NUMERIC = "NUMERIC"
    TEXT = "TEXT"
    BOOLEAN = "BOOLEAN"
    CODED = "CODED"


class ObservationStatus(StrEnum):
    FINAL = "FINAL"
    AMENDED = "AMENDED"
    ENTERED_IN_ERROR = "ENTERED_IN_ERROR"


class LaboratoryOrderStatus(StrEnum):
    REGISTERED = "REGISTERED"
    IN_PROGRESS = "IN_PROGRESS"
    CANCELLED = "CANCELLED"
    ENTERED_IN_ERROR = "ENTERED_IN_ERROR"


class LaboratorySpecimenType(StrEnum):
    BLOOD = "BLOOD"
    URINE = "URINE"
    SWAB = "SWAB"
    OTHER = "OTHER"


class LaboratorySpecimenStatus(StrEnum):
    COLLECTED = "COLLECTED"
    REJECTED = "REJECTED"
    ENTERED_IN_ERROR = "ENTERED_IN_ERROR"


class LaboratoryResultStatus(StrEnum):
    FINAL = "FINAL"
    AMENDED = "AMENDED"
    ENTERED_IN_ERROR = "ENTERED_IN_ERROR"


class LaboratoryResultValueType(StrEnum):
    NUMERIC = "NUMERIC"
    TEXT = "TEXT"
    BOOLEAN = "BOOLEAN"
    CODED = "CODED"


class LaboratoryResultInterpretation(StrEnum):
    NORMAL = "NORMAL"
    ABNORMAL = "ABNORMAL"
    CRITICAL = "CRITICAL"


class MedicationCategory(StrEnum):
    PRESCRIBED = "PRESCRIBED"
    REPORTED = "REPORTED"


class MedicationStatus(StrEnum):
    ACTIVE = "ACTIVE"
    STOPPED = "STOPPED"
    ENTERED_IN_ERROR = "ENTERED_IN_ERROR"


class MedicationRoute(StrEnum):
    ORAL = "ORAL"
    IV = "IV"
    IM = "IM"
    SC = "SC"
    TOPICAL = "TOPICAL"
    INHALED = "INHALED"
    OTHER = "OTHER"


class AllergyCategory(StrEnum):
    DRUG = "DRUG"
    FOOD = "FOOD"
    ENVIRONMENT = "ENVIRONMENT"
    OTHER = "OTHER"


class AllergyStatus(StrEnum):
    ACTIVE = "ACTIVE"
    AMENDED = "AMENDED"
    ENTERED_IN_ERROR = "ENTERED_IN_ERROR"


class AllergyClinicalStatus(StrEnum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"


class AllergyVerificationStatus(StrEnum):
    UNCONFIRMED = "UNCONFIRMED"
    CONFIRMED = "CONFIRMED"
    REFUTED = "REFUTED"


class AllergyCriticality(StrEnum):
    LOW = "LOW"
    HIGH = "HIGH"
    UNABLE_TO_ASSESS = "UNABLE_TO_ASSESS"


class AllergySeverity(StrEnum):
    MILD = "MILD"
    MODERATE = "MODERATE"
    SEVERE = "SEVERE"


class ClinicalProvenanceSubjectType(StrEnum):
    ENCOUNTER = "ENCOUNTER"
    CLINICAL_NOTE = "CLINICAL_NOTE"
    CONDITION = "CONDITION"
    OBSERVATION = "OBSERVATION"
    LABORATORY_ORDER = "LABORATORY_ORDER"
    LABORATORY_SPECIMEN = "LABORATORY_SPECIMEN"
    LABORATORY_RESULT = "LABORATORY_RESULT"
    MEDICATION = "MEDICATION"
    ALLERGY = "ALLERGY"


class ClinicalAuditAction(StrEnum):
    ENCOUNTER_CREATED = "ENCOUNTER_CREATED"
    ENCOUNTER_STATUS_CHANGED = "ENCOUNTER_STATUS_CHANGED"
    CLINICAL_NOTE_CREATED = "CLINICAL_NOTE_CREATED"
    CLINICAL_NOTE_UPDATED = "CLINICAL_NOTE_UPDATED"
    CLINICAL_NOTE_FINALIZED = "CLINICAL_NOTE_FINALIZED"
    CLINICAL_NOTE_ENTERED_IN_ERROR = "CLINICAL_NOTE_ENTERED_IN_ERROR"
    CONDITION_CREATED = "CONDITION_CREATED"
    CONDITION_STATUS_CHANGED = "CONDITION_STATUS_CHANGED"
    CONDITION_ENTERED_IN_ERROR = "CONDITION_ENTERED_IN_ERROR"
    OBSERVATION_CREATED = "OBSERVATION_CREATED"
    OBSERVATION_AMENDED = "OBSERVATION_AMENDED"
    OBSERVATION_ENTERED_IN_ERROR = "OBSERVATION_ENTERED_IN_ERROR"
    LAB_ORDER_CREATED = "LAB_ORDER_CREATED"
    LAB_ORDER_IN_PROGRESS = "LAB_ORDER_IN_PROGRESS"
    LAB_ORDER_CANCELLED = "LAB_ORDER_CANCELLED"
    LAB_ORDER_ENTERED_IN_ERROR = "LAB_ORDER_ENTERED_IN_ERROR"
    LAB_SPECIMEN_COLLECTED = "LAB_SPECIMEN_COLLECTED"
    LAB_SPECIMEN_REJECTED = "LAB_SPECIMEN_REJECTED"
    LAB_SPECIMEN_ENTERED_IN_ERROR = "LAB_SPECIMEN_ENTERED_IN_ERROR"
    LAB_RESULT_CREATED = "LAB_RESULT_CREATED"
    LAB_RESULT_AMENDED = "LAB_RESULT_AMENDED"
    LAB_RESULT_ENTERED_IN_ERROR = "LAB_RESULT_ENTERED_IN_ERROR"
    MEDICATION_CREATED = "MEDICATION_CREATED"
    MEDICATION_STOPPED = "MEDICATION_STOPPED"
    MEDICATION_ENTERED_IN_ERROR = "MEDICATION_ENTERED_IN_ERROR"
    ALLERGY_CREATED = "ALLERGY_CREATED"
    ALLERGY_AMENDED = "ALLERGY_AMENDED"
    ALLERGY_ENTERED_IN_ERROR = "ALLERGY_ENTERED_IN_ERROR"
