from enum import StrEnum


class ProviderCapabilityState(StrEnum):
    AVAILABLE = "AVAILABLE"
    SUSPENDED = "SUSPENDED"
    RETIRED = "RETIRED"


class ProfileVersionStatus(StrEnum):
    DRAFT = "DRAFT"
    PUBLISHED = "PUBLISHED"
    SUPERSEDED = "SUPERSEDED"


class FeatureActivationState(StrEnum):
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED = "APPROVED"
    ACTIVE = "ACTIVE"
    SUSPENDED = "SUSPENDED"
    RETIRED = "RETIRED"


class DeploymentGateType(StrEnum):
    CONTROLLER_PROCESSOR_ASSESSMENT = "CONTROLLER_PROCESSOR_ASSESSMENT"
    DPA = "DPA"


class DeploymentGateState(StrEnum):
    NOT_ASSESSED = "NOT_ASSESSED"
    PENDING = "PENDING"
    SATISFIED = "SATISFIED"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    EXPIRED = "EXPIRED"


class ApprovalEvidenceStatus(StrEnum):
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    WITHDRAWN = "WITHDRAWN"
    SUPERSEDED = "SUPERSEDED"


class GovernanceAdminScopeType(StrEnum):
    ORGANIZATION = "ORGANIZATION"
    PLATFORM = "PLATFORM"


class GovernanceAdminOperation(StrEnum):
    PROFILE_VERSION_CREATE = "GOVERNANCE_PROFILE_VERSION_CREATE"
    PROFILE_VERSION_PUBLISH = "GOVERNANCE_PROFILE_VERSION_PUBLISH"
    APPROVAL_EVIDENCE_RECORD = "GOVERNANCE_APPROVAL_EVIDENCE_RECORD"


class GovernanceAuditAction(StrEnum):
    PROFILE_VERSION_CREATED = "GOVERNANCE_PROFILE_VERSION_CREATED"
    PROFILE_VERSION_PUBLISHED = "GOVERNANCE_PROFILE_VERSION_PUBLISHED"
    APPROVAL_EVIDENCE_RECORDED = "GOVERNANCE_APPROVAL_EVIDENCE_RECORDED"
    APPROVAL_EVIDENCE_WITHDRAWN = "GOVERNANCE_APPROVAL_EVIDENCE_WITHDRAWN"
    FEATURE_ACTIVATION_CHANGED = "GOVERNANCE_FEATURE_ACTIVATION_CHANGED"
    DEPLOYMENT_GATE_CHANGED = "GOVERNANCE_DEPLOYMENT_GATE_CHANGED"
    PROVIDER_CAPABILITY_CHANGED = "GOVERNANCE_PROVIDER_CAPABILITY_CHANGED"


class GovernanceDenialReason(StrEnum):
    NOT_REGISTERED = "NOT_REGISTERED"
    DENIED_PROVIDER = "DENIED_PROVIDER"
    DENIED_ENTITLEMENT = "DENIED_ENTITLEMENT"
    DENIED_DEPLOYMENT_GATE = "DENIED_DEPLOYMENT_GATE"
    DENIED_SITE_ACTIVATION = "DENIED_SITE_ACTIVATION"
    DENIED_POLICY = "DENIED_POLICY"
    DENIED_PERMISSION = "DENIED_PERMISSION"
    DENIED_CONTEXT = "DENIED_CONTEXT"


class PolicyEffect(StrEnum):
    ALLOW = "ALLOW"
    DENY = "DENY"
