/** Frozen catalog snapshots for navigation tests. Not a second authorization engine. */

export const registrarCatalog = [
  "iam.user.read",
  "org.organization.read",
  "org.facility.read",
  "mpi.identity.create",
  "mpi.identity.read",
  "mpi.identifier.add",
  "mpi.match.evaluate",
  "clinical.encounter.create",
  "clinical.encounter.read",
];

export const identityOfficerCatalog = [
  "iam.user.read",
  "org.organization.read",
  "org.facility.read",
  "mpi.identity.create",
  "mpi.identity.read",
  "mpi.identifier.add",
  "mpi.identifier.verify",
  "mpi.match.evaluate",
  "mpi.match.review",
  "mpi.merge.execute",
  "mpi.unmerge.execute",
];

export const auditorCatalog = [
  "iam.user.read",
  "org.organization.read",
  "org.facility.read",
  "mpi.identity.read",
  "clinical.encounter.read",
  "clinical.note.read",
  "clinical.condition.read",
  "clinical.observation.read",
  "clinical.laboratory.order.read",
  "clinical.laboratory.specimen.read",
  "clinical.laboratory.result.read",
  "clinical.medication.read",
  "clinical.allergy.read",
  "clinical.consent.read",
  "clinical.immunization.read",
  "clinical.procedure.read",
  "clinical.medical_device.read",
  "clinical.adverse_event.read",
  "clinical.family_history.read",
];

export const orgAdminCatalog = [
  "iam.user.read",
  "iam.membership.manage",
  "org.organization.read",
  "org.facility.create",
  "org.facility.read",
  "org.identifier.manage",
  "mpi.identity.read",
  ...auditorCatalog.filter((code) => code.startsWith("clinical.")),
];

export const clinicianCatalog = [
  "iam.user.read",
  "org.organization.read",
  "org.facility.read",
  "mpi.identity.read",
  "clinical.encounter.create",
  "clinical.encounter.read",
  "clinical.encounter.update_status",
  "clinical.note.create",
  "clinical.note.read",
  "clinical.note.update_draft",
  "clinical.note.finalize",
  "clinical.condition.create",
  "clinical.condition.read",
  "clinical.condition.update",
  "clinical.condition.entered_in_error",
  "clinical.observation.create",
  "clinical.observation.read",
  "clinical.observation.update",
  "clinical.observation.entered_in_error",
  "clinical.laboratory.order.create",
  "clinical.laboratory.order.read",
  "clinical.laboratory.order.update",
  "clinical.laboratory.order.entered_in_error",
  "clinical.laboratory.specimen.create",
  "clinical.laboratory.specimen.read",
  "clinical.laboratory.specimen.update",
  "clinical.laboratory.specimen.entered_in_error",
  "clinical.laboratory.result.create",
  "clinical.laboratory.result.read",
  "clinical.laboratory.result.update",
  "clinical.laboratory.result.entered_in_error",
  "clinical.medication.create",
  "clinical.medication.read",
  "clinical.medication.update",
  "clinical.medication.entered_in_error",
  "clinical.allergy.create",
  "clinical.allergy.read",
  "clinical.allergy.update",
  "clinical.allergy.entered_in_error",
  "clinical.consent.create",
  "clinical.consent.read",
  "clinical.consent.update",
  "clinical.consent.revoke",
  "clinical.consent.entered_in_error",
  "clinical.immunization.create",
  "clinical.immunization.read",
  "clinical.immunization.update",
  "clinical.immunization.entered_in_error",
  "clinical.procedure.create",
  "clinical.procedure.read",
  "clinical.procedure.update",
  "clinical.procedure.entered_in_error",
  "clinical.medical_device.create",
  "clinical.medical_device.read",
  "clinical.medical_device.update",
  "clinical.medical_device.entered_in_error",
  "clinical.adverse_event.create",
  "clinical.adverse_event.read",
  "clinical.adverse_event.update",
  "clinical.adverse_event.entered_in_error",
  "clinical.family_history.create",
  "clinical.family_history.read",
  "clinical.family_history.update",
  "clinical.family_history.entered_in_error",
];
